import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Services from '@/components/Services'
import Slider from '../components/Slider'
import ScrollButton from '@/components/ScrollButton'
import Contact from './contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ScrollButton/>
      {/* <Navbar/> */}
      <Slider/>
      {/* <Contact/> */}
      {/* <ProductList  items={props.events}/> */}
      <Services/>
    </>
  )
}
